apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: article01-ubw
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/article01-ubw
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client