apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-h>5
  namespace: ghost-h>5
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi