apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost3-8ab
  namespace: ghost3-8ab
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi