apiVersion: v1
kind: Service
metadata:
  name: ghost3-8ab
  namespace: ghost3-8ab
spec:
  type: ClusterIP
  selector:
    app: ghost3-8ab
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368