apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: article01-ubw
  namespace: article01-ubw
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi