apiVersion: v1
kind: Service
metadata:
  name: article01-ubw
  namespace: article01-ubw
spec:
  type: ClusterIP
  selector:
    app: article01-ubw
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368