apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-aqv
  namespace: ghost-aqv
  labels:
    app: ghost-aqv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-aqv
  template:
    metadata:
      labels:
        app: ghost-aqv
    spec:
      containers:
      - name: ghost-aqv
        image: ghost
        env:
        - name: url
          value: https://ade-kaas-demo.westeurope.cloudapp.azure.com/ghost-aqv
        - name: NODE_ENV
          value: development
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        ports:
        - name: http
          containerPort: 2368
          protocol: TCP
      restartPolicy: Always