apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-claim
  namespace: ghost
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi