apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-m8j
  namespace: ghost-m8j
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi