apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost2-XpmG
  namespace: ghost2-XpmG
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi