apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-fl9
  namespace: ghost-fl9
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi