apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost2-hbsi
  namespace: ghost2-hbsi
spec:
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  resources:
    requests:
      storage: 50Gi